# Generated by Django 4.2.7 on 2023-11-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
