# Generated by Django 4.2.7 on 2023-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0007_customer_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
