# Generated by Django 4.2.7 on 2023-11-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0008_alter_customer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
