# Generated by Django 4.2.7 on 2023-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0010_delete_user_id_alter_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
