# Generated by Django 4.2.7 on 2023-11-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0013_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
